### ISSUE TITLE
Firmware - Add MAC Address into the MQTT Topic

### ISSUE THREAD

**Issue by acremonezi** [acremonezi/Projeto-Integrador-em-Computacao-III#18]

**Comment by acremonezi** [comment]
Done!
**New Payload Information added:**

![image](https://user-images.githubusercontent.com/32877060/191413759-d87ba4ac-cad2-48cd-a8d3-419aa6ea5e94.png)

**Comment by acremonezi** [comment]
**I am Blocked!!! Please Help!!!** @ioFormigoni @2005869 
`Explanation is on line 19 at ./hardware/src/mqtt/mqtt.cpp`

**Comment by ioFormigoni** [comment]
You can merge without closing an issue -> reopening issue
